version: "3.9"
services:
  db:
      image: postgres
      environment:
          - POSTGRES_DB='${POSTGRES_DB}'
          - POSTGRES_USER='${POSTGRES_USER}'
          - POSTGRES_PASSWORD='${POSTGRES_USER}'
  web:
    build: .
    hostname: web
    volumes:
        - ./app:/app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
