version: "3.9"
services:
  db:
      image: postgres
      env_file:
        - postgres-variables.env

  web:
    build: .
    hostname: web
    volumes:
        - ./app:/app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
