# Generated by Django 3.2 on 2021-05-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0002_auto_20210428_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
