# Generated by Django 3.2 on 2021-05-29 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0003_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
