# Generated by Django 3.2 on 2021-06-30 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0006_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='hour',
            field=models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(),
        ),
    ]
