# Generated by Django 3.2 on 2021-06-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0007_auto_20210630_0555'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('date', 'hour')},
        ),
    ]
